# Generated by Django 5.0.6 on 2024-06-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ingredient_unit_alter_ingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.IntegerField(default=0),
        ),
    ]
