# Generated by Django 5.0.6 on 2024-06-03 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_ingredient_id_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='create_date',
        ),
    ]
